[platformio]
default_envs = m5stickcplus2

[env:m5stickcplus2]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
lib_deps =
  m5stack/M5Unified
  bblanchon/ArduinoJson
  tzapu/WiFiManager
build_flags =
  -D WLED_REMOTE_VERSION=\"0.1.0-alpha\"
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D WM_NODEBUG
  -std=gnu++14
build_unflags =
  -std=gnu++11
